default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5
  port: 5433

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test
